-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 17:21:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_escola2
-- -----------------------------------------------------
-- gerando agora pela interface gráfica

-- -----------------------------------------------------
-- Schema db_escola2
--
-- gerando agora pela interface gráfica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_escola2` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_escola2` ;

-- -----------------------------------------------------
-- Table `db_escola2`.`tb_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_escola2`.`tb_turmas` (
  `nome` VARCHAR(25) NOT NULL,
  `turma_id` INT NOT NULL,
  PRIMARY KEY (`turma_id`),
  UNIQUE INDEX `ra_UNIQUE` (`turma_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_escola2`.`tb_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_escola2`.`tb_alunos` (
  `id_aluno` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `ra` INT NOT NULL,
  `nota` DECIMAL NOT NULL,
  `turma_id` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `id_aluno_UNIQUE` (`id_aluno` ASC) VISIBLE,
  UNIQUE INDEX `ra_UNIQUE` (`ra` ASC) VISIBLE,
  INDEX `turma_id_idx` (`turma_id` ASC) VISIBLE,
  CONSTRAINT `turma_id`
    FOREIGN KEY (`turma_id`)
    REFERENCES `db_escola2`.`tb_turmas` (`turma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `db_escola2`.`tb_turmas` (`nome`, `turma_id`) VALUES ('Turma 20', '20');
INSERT INTO `db_escola2`.`tb_alunos` ( `nome`, `ra`, `nota`, `turma_id`) VALUES ('Ingrid', '1234', '10', '20');