-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 17:46:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_loja2
-- -----------------------------------------------------
-- criando pela interface gráfica

-- -----------------------------------------------------
-- Schema db_loja2
--
-- criando pela interface gráfica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_loja2` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_loja2` ;

-- -----------------------------------------------------
-- Table `db_loja2`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja2`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `marca_id` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `categoria_id` VARCHAR(45) NOT NULL,
  `tb_produtocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja2`.`tb_marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja2`.`tb_marcas` (
  `id_marca` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tb_produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_marca`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_marca` ASC) VISIBLE,
  INDEX `fk_tb_marcas_tb_produto_idx` (`tb_produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_marcas_tb_produto`
    FOREIGN KEY (`tb_produto_id_produto`)
    REFERENCES `db_loja2`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja2`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja2`.`tb_categoria` (
  `id_categoria` INT NOT NULL,
  `categoria_id` VARCHAR(45) NOT NULL,
  `tb_produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_categoria`, `tb_produto_id_produto`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_tb_categoria_tb_produto1_idx` (`tb_produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_categoria_tb_produto1`
    FOREIGN KEY (`tb_produto_id_produto`)
    REFERENCES `db_loja2`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
